# Generated by Django 4.1.5 on 2023-03-16 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insurance', '0002_resume'),
    ]

    operations = [
        migrations.AlterField(
            model_name='joblisting',
            name='job_location',
            field=models.CharField(choices=[('Harare', 'Harare'), ('Bulawayo', 'Bulawayo'), ('Chinhoyi', 'Chinhoyi'), ('Mutare', 'Mutare')], max_length=120),
        ),
    ]
