# Generated by Django 4.1.5 on 2023-03-16 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insurance', '0003_alter_joblisting_job_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='joblisting',
            name='status',
            field=models.IntegerField(default=1),
        ),
    ]
