# Generated by Django 4.1.5 on 2023-03-16 09:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('insurance', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resume', models.FileField(upload_to='resumes/', verbose_name='Upload Resumes')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Name')),
                ('email', models.CharField(blank=True, max_length=255, null=True, verbose_name='Email')),
                ('mobile_number', models.CharField(blank=True, max_length=255, null=True, verbose_name='Mobile Number')),
                ('education', models.CharField(blank=True, max_length=255, null=True, verbose_name='Education')),
                ('skills', models.CharField(blank=True, max_length=1000, null=True, verbose_name='Skills')),
                ('company_name', models.CharField(blank=True, max_length=1000, null=True, verbose_name='Company Name')),
                ('college_name', models.CharField(blank=True, max_length=1000, null=True, verbose_name='College Name')),
                ('designation', models.CharField(blank=True, max_length=1000, null=True, verbose_name='Designation')),
                ('experience', models.CharField(blank=True, max_length=1000, null=True, verbose_name='Experience')),
                ('uploaded_on', models.DateTimeField(auto_now_add=True, verbose_name='Uploaded On')),
                ('total_experience', models.CharField(blank=True, max_length=1000, null=True, verbose_name='Total Experience (in Years)')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='insurance.joblisting')),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_pic', models.ImageField(blank=True, null=True, upload_to='profile_pic/Customer/')),
                ('address', models.CharField(max_length=40)),
                ('mobile', models.CharField(max_length=20)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ApplyJob',
            fields=[
                ('apply_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('phone', models.CharField(max_length=11)),
                ('email', models.EmailField(max_length=254)),
                ('file', models.FileField(null=True, upload_to='')),
                ('application_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('status', models.CharField(choices=[('Approved', 'APPROVED'), ('Rejected', 'REJECTED'), ('Pending', 'PENDING')], default='Pending', max_length=255)),
                ('remarks', models.CharField(max_length=255, null=True)),
                ('applicant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer.customer')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='insurance.joblisting')),
            ],
        ),
    ]
