# Generated by Django 4.1.5 on 2023-03-16 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applyjob',
            name='remarks',
            field=models.CharField(default='Pending Assessment', max_length=255),
        ),
    ]
