# Generated by Django 4.1.5 on 2023-03-16 19:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0002_alter_applyjob_remarks'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Resume',
        ),
    ]
