# Generated by Django 4.1.5 on 2023-03-16 20:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0003_delete_resume'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='profile_pic',
        ),
    ]
